name: Build AtmoPackUpdater

on:
  push:
  workflow_dispatch:

jobs:
  AtmoPackUpdater:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1

    - name: update repo
      run: |
        git config --global --add safe.directory /__w/AtmoPackUpdater/AtmoPackUpdater/lib/borealis
        git config --global --add safe.directory /__w/AtmoPackUpdater/AtmoPackUpdater
        git submodule update --init --recursive
            
    - name: build AtmoPackUpdater
      run: | 
        make
      
    - uses: actions/upload-artifact@master
      with:
        name: AtmoPackUpdater
        path: AtmoPackUpdater.nro

